name: johnshin
favicon: null
layout_spectrum: 0.19763
typography_spectrum: 0.27315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#454545'
    - '#797979'
    - '#0a0a0a'
    - '#989898'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
