name: johnshin
favicon: null
layout_spectrum: 0.4614096006844193
typography_spectrum: 0.2814969371538609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.505816821474582
  lightness: 0.5436146352440119
  saturation: 0.6013781495857984
  rhythmicContrast: 0.0996006946079433
purpose: []
